package pe.telefonica.customerordermanagement.orderservices.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-11T13:55:15.942-05:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "OrderServicesService",
                  wsdlLocation = "file:/C:/synopsis/motor/ofertas-elegibles-moviles/shaka-elegiblefoffers-mo/src/main/resources/wsdl/cp/v1.wsdl",
                  targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1")
public class OrderServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://telefonica.pe/CustomerOrderManagement/OrderServices/V1", "OrderServicesService");
    public final static QName OrderServicesPortType = new QName("http://telefonica.pe/CustomerOrderManagement/OrderServices/V1", "orderServicesPortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/synopsis/motor/ofertas-elegibles-moviles/shaka-elegiblefoffers-mo/src/main/resources/wsdl/cp/v1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderServicesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/synopsis/motor/ofertas-elegibles-moviles/shaka-elegiblefoffers-mo/src/main/resources/wsdl/cp/v1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrderServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrderServicesPortType
     */
    @WebEndpoint(name = "orderServicesPortType")
    public OrderServicesPortType getOrderServicesPortType() {
        return super.getPort(OrderServicesPortType, OrderServicesPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderServicesPortType
     */
    @WebEndpoint(name = "orderServicesPortType")
    public OrderServicesPortType getOrderServicesPortType(WebServiceFeature... features) {
        return super.getPort(OrderServicesPortType, OrderServicesPortType.class, features);
    }

}
