package pe.telefonica.customerordermanagement.orderservices.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-09T14:39:37.783-05:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1", name = "orderServicesPortType")
@XmlSeeAlso({pe.telefonica.customerordermanagement.orderservices.v1.types.ObjectFactory.class, pe.telefonica.tefrequestheader.v1.ObjectFactory.class, pe.telefonica.teferror.v1.ObjectFactory.class, pe.telefonica.tefresponseheader.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderServicesPortType {

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/requestSVADeactivation")
    @WebResult(name = "RequestSVADeactivationResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RequestSVADeactivationResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVADeactivationResponseType requestSVADeactivation(

        @WebParam(partName = "RequestSVADeactivationRequest", name = "RequestSVADeactivationRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVADeactivationRequestType requestSVADeactivationRequest
    ) throws RequestSVADeactivationFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/modifyService")
    @WebResult(name = "ModifyServiceResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "ModifyServiceResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.ModifyServiceResponseType modifyService(

        @WebParam(partName = "ModifyServiceRequest", name = "ModifyServiceRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.ModifyServiceRequestType modifyServiceRequest
    ) throws ModifyServiceFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/retrieveProductHeader")
    @WebResult(name = "RetrieveProductHeaderResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RetrieveProductHeaderResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveProductHeaderResponseType retrieveProductHeader(

        @WebParam(partName = "RetrieveProductHeaderRequest", name = "RetrieveProductHeaderRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveProductHeaderRequestType retrieveProductHeaderRequest
    ) throws RetrieveProductHeaderFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/retrieveFriendsAndFamilyNumbers")
    @WebResult(name = "RetrieveFriendsAndFamilyNumbersResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RetrieveFriendsAndFamilyNumbersResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveFriendsAndFamilyNumbersResponseType retrieveFriendsAndFamilyNumbers(

        @WebParam(partName = "RetrieveFriendsAndFamilyNumbersRequest", name = "RetrieveFriendsAndFamilyNumbersRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveFriendsAndFamilyNumbersRequestType retrieveFriendsAndFamilyNumbersRequest
    ) throws RetrieveFriendsAndFamilyNumbersFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/validateTokenFnF")
    @WebResult(name = "ValidateTokenFnFResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "ValidateTokenFnFResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.ValidateTokenFnFResponseType validateTokenFnF(

        @WebParam(partName = "ValidateTokenFnFRequest", name = "ValidateTokenFnFRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.ValidateTokenFnFRequestType validateTokenFnFRequest
    ) throws ValidateTokenFnFFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/retrieveCommitmentPenalty")
    @WebResult(name = "RetrieveCommitmentPenaltyResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RetrieveCommitmentPenaltyResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveCommitmentPenaltyResponseType retrieveCommitmentPenalty(

        @WebParam(partName = "RetrieveCommitmentPenaltyRequest", name = "RetrieveCommitmentPenaltyRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveCommitmentPenaltyRequestType retrieveCommitmentPenaltyRequest
    ) throws RetrieveCommitmentPenaltyFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/addOrRemoveBillingOffer")
    @WebResult(name = "AddOrRemoveBillingOfferResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "AddOrRemoveBillingOfferResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.AddOrRemoveBillingOfferResponseType addOrRemoveBillingOffer(

        @WebParam(partName = "AddOrRemoveBillingOfferRequest", name = "AddOrRemoveBillingOfferRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.AddOrRemoveBillingOfferRequestType addOrRemoveBillingOfferRequest
    ) throws AddOrRemoveBillingOfferFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/retrieveOrdersHistory")
    @WebResult(name = "RetrieveOrdersHistoryResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "retrieveOrdersHistoryResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveOrdersHistoryResponseType retrieveOrdersHistory(

        @WebParam(partName = "retrieveOrdersHistoryRequest", name = "RetrieveOrdersHistoryRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveOrdersHistoryRequestType retrieveOrdersHistoryRequest
    ) throws RetrieveOrdersHistoryFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/querySubscriptionGroupValue")
    @WebResult(name = "QuerySubscriptionGroupValueResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "QuerySubscriptionGroupValueResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.QuerySubscriptionGroupValueResponseType querySubscriptionGroupValue(

        @WebParam(partName = "QuerySubscriptionGroupValueRequest", name = "QuerySubscriptionGroupValueRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.QuerySubscriptionGroupValueRequestType querySubscriptionGroupValueRequest
    ) throws QuerySubscriptionGroupValueFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/retrieveProductOrderStatus")
    @WebResult(name = "RetrieveProductOrderStatusResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RetrieveProductOrderStatusResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveProductOrderStatusResponseType retrieveProductOrderStatus(

        @WebParam(partName = "RetrieveProductOrderStatusRequest", name = "RetrieveProductOrderStatusRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveProductOrderStatusRequestType retrieveProductOrderStatusRequest
    ) throws RetrieveProductOrderStatusFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/requestSVAActivation")
    @WebResult(name = "RequestSVAActivationResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RequestSVAActivationResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVAActivationResponseType requestSVAActivation(

        @WebParam(partName = "RequestSVAActivationRequest", name = "RequestSVAActivationRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVAActivationRequestType requestSVAActivationRequest
    ) throws RequestSVAActivationFault;

    @WebMethod
    @WebResult(name = "LocateSubscriptionResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "LocateSubscriptionResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.LocateSubscriptionResponseType locateSubscription(

        @WebParam(partName = "LocateSubscriptionRequest", name = "LocateSubscriptionRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.LocateSubscriptionRequestType locateSubscriptionRequest
    ) throws UpdateFriendsAndFamilyNumbersRequest;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/updateSingleConfigurationOnProduct")
    @WebResult(name = "UpdateSingleConfigurationOnProductResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "UpdateSingleConfigurationOnProductResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.UpdateSingleConfigurationOnProductResponseType updateSingleConfigurationOnProduct(

        @WebParam(partName = "UpdateSingleConfigurationOnProductRequest", name = "UpdateSingleConfigurationOnProductRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.UpdateSingleConfigurationOnProductRequestType updateSingleConfigurationOnProductRequest
    ) throws UpdateSingleConfigurationOnProductFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/updateFriendsAndFamilyNumbers")
    @WebResult(name = "UpdateFriendsAndFamilyNumbersResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "UpdateFriendsAndFamilyNumbersResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.UpdateFriendsAndFamilyNumbersResponseType updateFriendsAndFamilyNumbers(

        @WebParam(partName = "UpdateFriendsAndFamilyNumbersRequest", name = "UpdateFriendsAndFamilyNumbersRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.UpdateFriendsAndFamilyNumbersRequestType updateFriendsAndFamilyNumbersRequest
    ) throws UpdateFriendsAndFamilyNumbersFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/retrieveServiceByMask")
    @WebResult(name = "RetrieveServiceByMaskResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RetrieveServiceByMaskResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveServiceByMaskResponseType retrieveServiceByMask(

        @WebParam(partName = "RetrieveServiceByMaskRequest", name = "RetrieveServiceByMaskRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveServiceByMaskRequestType retrieveServiceByMaskRequest
    ) throws RetrieveServiceByMaskFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/changeProductStatus")
    @WebResult(name = "ChangeProductStatusResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "ChangeProductStatusResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.ChangeProductStatusResponseType changeProductStatus(

        @WebParam(partName = "ChangeProductStatusRequest", name = "ChangeProductStatusRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.ChangeProductStatusRequestType changeProductStatusRequest
    ) throws ChangeProductStatusFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/changeFunPack")
    @WebResult(name = "ChangeFunPackResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "ChangeFunPackResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.ChangeFunPackResponseType changeFunPack(

        @WebParam(partName = "ChangeFunPackRequest", name = "ChangeFunPackRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.ChangeFunPackRequestType changeFunPackRequest
    ) throws ChangeFunPackFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/createTokenFnF")
    @WebResult(name = "CreateTokenFnFResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "CreateTokenFnFResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.CreateTokenFnFResponseType createTokenFnF(

        @WebParam(partName = "CreateTokenFnFRequest", name = "CreateTokenFnFRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.CreateTokenFnFRequestType createTokenFnFRequest
    ) throws CreateTokenFnFFault;

    @WebMethod(action = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/retrieveExternalStockUnit")
    @WebResult(name = "RetrieveExternalStockUnitResponse", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types", partName = "RetrieveExternalStockUnitResponse")
    public pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveExternalStockUnitResponseType retrieveExternalStockUnit(

        @WebParam(partName = "RetrieveExternalStockUnitRequest", name = "RetrieveExternalStockUnitRequest", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
        pe.telefonica.customerordermanagement.orderservices.v1.types.RetrieveExternalStockUnitRequestType retrieveExternalStockUnitRequest
    ) throws RetrieveExternalStockUnitFault;
}
