
package pe.telefonica.customerordermanagement.orderservices.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-11T13:55:15.753-05:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "RequestSVAActivationFault", targetNamespace = "http://telefonica.pe/CustomerOrderManagement/OrderServices/V1/types")
public class RequestSVAActivationFault extends Exception {

    private pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVAActivationFault requestSVAActivationFault;

    public RequestSVAActivationFault() {
        super();
    }

    public RequestSVAActivationFault(String message) {
        super(message);
    }

    public RequestSVAActivationFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RequestSVAActivationFault(String message, pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVAActivationFault requestSVAActivationFault) {
        super(message);
        this.requestSVAActivationFault = requestSVAActivationFault;
    }

    public RequestSVAActivationFault(String message, pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVAActivationFault requestSVAActivationFault, java.lang.Throwable cause) {
        super(message, cause);
        this.requestSVAActivationFault = requestSVAActivationFault;
    }

    public pe.telefonica.customerordermanagement.orderservices.v1.types.RequestSVAActivationFault getFaultInfo() {
        return this.requestSVAActivationFault;
    }
}
